#%RAML 1.0
---
title: Perseus 
baseURI: http://{IP Address}/

types:          !include types.raml

/broadcast:     !include broadcast.raml
/results:       !include results.raml
/session:       !include session.raml
/starters:      !include startlist.raml
