#%RAML 1.0
---
title:        Local Results System (Codename: Perseus) API 
baseURI:      http://{IP Address}/perseus
description:  API description for competitor registration methods
  
/registration:
  /file:
    post:
      description:      Upload a csv file containing the details of climbers registered for the competition 
      queryParameters:
        file:
          type:         file
          description:  CSV file with headers
          example: |
              per_id, lastname, firstname, federation, nation, birthyear
              6550, Bacher, Barbara, OEAV Inneroetztal, AUT, 1980
          required:     true
      responses:
        200:
        501:
  /ifsc:
    post:
      description:      Fetch a list of registered climbers from eGroupware
      queryParameters:
        wet_id:
          type:         integer
          description:  A unique value identifying the competition
          example:      1499
          required:     true
      responses:
        200:
        501:

