#%RAML 1.0
---
title:        Perseus
baseURI:      http://{IP Address}/session
description:  API description to get/set session parameters for the application

get:
  description: Fetch session parameters (the current competition and any eGroupware authorisation)
  responses:
    200:
      body:
        application/json:
          type:         object
          description:  A JSON formatted results object
          example:
            {
              'wet_id': 1499,
              'auth': 'sessionid=qo5tji64a1cvobtkddnjktlth0'
            }
post:
  description: Set session parameters (the current competition and/or an eGroupware authorisation)
  queryParameters: 
    wet_id?:        wet_id
    auth?:
      type:         string
      description:  An eGroupware sessionid parameter
      example:      sessionid=qo5tji64a1cvobtkddnjktlth0 
  responses:
    200:
      description:  Message successfully processed by server
    404:
      description:  Connection error
    501:
      description:  Server error
delete:
  description: Reset (purge) the session parameters
  responses:
    200:
      description:  Message successfully processed by server
    404:
      description:  Connection error
    501:
      description:  Server error
/connection:
  get:
    description: Get the hostname and IP address assigned to the local server
    responses:
      200:
        body:
          application/json:
            type:     object
            description:  A JSON formatted results object
            example:  |
              {
                hostname: 'copper.aircard',
                address: '192.169.1.90'
              }
