#%RAML 1.0
---
title:        Perseus 
baseURI:      http://{IP Address}/startlist
description:  API description for competitor registration methods
  
/file:
  post:
    description: |
      Create a startlist from a csv file containing a list of the competitors - 
      per_id, start_order, rank_prev_heat
    queryParameters:
      wet_id:       wet_id
      grp_id:       grp_id
      route:        route
      file:
        type:         file
        description:  CSV file with headers
        required:     true
        example: |
            per_id, start_order, rank_prev_heat
            1030, 1, null
    responses:
      200:
        description:  Message successfully processed by server
      404:
        description:  Connection error
      501:
        description:  Server error
/ifsc:
  post:
    description:
    queryParameters:
      wet_id:       wet_id
      grp_id:       grp_id
      route:        route
    responses:
      200:
        description:  Message successfully processed by server
      404:
        description:  Connection error
      501:
        description:  Server error
/registration:
  /file:
    post:
      description:      Upload a csv file containing the details of climbers registered for the competition 
      queryParameters:
        file:
          type:         file
          description:  CSV file with headers
          example: |
              per_id, lastname, firstname, federation, nation, birthyear
              6550, Bacher, Barbara, OEAV Inneroetztal, AUT, 1980
          required:     true
      responses:
        200:
          description:  Message successfully processed by server
        404:
          description:  Connection error
        501:
          description:  Server error
  /ifsc:
    post:
      description:      Fetch a list of registered climbers from eGroupware
      queryParameters:
        wet_id:         wet_id
      responses:
        200:
          description:  Message successfully processed by server
        404:
          description:  Connection error
        501:
          description:  Server error
